// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBukUWDT3rBxdqtSLXTt6XKD9DFeMMG3D4',
    appId: '1:130375324659:web:25045672d84144c84d7886',
    messagingSenderId: '130375324659',
    projectId: 'flutter-firebase-8410e',
    authDomain: 'flutter-firebase-8410e.firebaseapp.com',
    storageBucket: 'flutter-firebase-8410e.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBYgEqWVXLDJUq2fO8-UKOXOkZOceSvnPk',
    appId: '1:130375324659:android:87b1d87b924514174d7886',
    messagingSenderId: '130375324659',
    projectId: 'flutter-firebase-8410e',
    storageBucket: 'flutter-firebase-8410e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAfXb010KFwRbYO1Br0Wn4QsZp9r3nBe9k',
    appId: '1:130375324659:ios:d15d335a2b6955714d7886',
    messagingSenderId: '130375324659',
    projectId: 'flutter-firebase-8410e',
    storageBucket: 'flutter-firebase-8410e.appspot.com',
    iosBundleId: 'com.example.emailAuth',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAfXb010KFwRbYO1Br0Wn4QsZp9r3nBe9k',
    appId: '1:130375324659:ios:aa17c9f759b2cab64d7886',
    messagingSenderId: '130375324659',
    projectId: 'flutter-firebase-8410e',
    storageBucket: 'flutter-firebase-8410e.appspot.com',
    iosBundleId: 'com.example.emailAuth.RunnerTests',
  );
}
